In [1]:
import numpy as np
A=np.array([[56.0,0.0,4.4,68.0],
            [1.2,104.0,52.0,8.0],
            [1.8,135.0,99.0,0.9]
])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [2]:
cal=A.sum(axis=0)

In [3]:
print(cal)

[ 59.  239.  155.4  76.9]


In [5]:
percentage=100*A/cal
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [6]:
# python and numpy vectors


In [7]:
a=np.random.randn(5)

In [8]:
print(a)
print(a.shape)

[ 0.21668244  2.11830365 -0.72969399  0.48642483  0.16116196]
(5,)


In [9]:
print(a.T)

[ 0.21668244  2.11830365 -0.72969399  0.48642483  0.16116196]


In [10]:
print(np.dot(a,a.T))

5.329197261765254


In [11]:
a=np.random.randn(5,1)
print(a)

[[ 0.94023477]
 [ 2.12197199]
 [-0.52885583]
 [ 1.857788  ]
 [-0.28912344]]


In [12]:
print(a.T)

[[ 0.94023477  2.12197199 -0.52885583  1.857788   -0.28912344]]
